import { catalog } from '../catalog/ksi.mjs';
import { rulesProvenance } from '../catalog/rules.mjs';
import { ALL_CHECKS } from '../collectors/registry.mjs';

/**
 * Generates a routing map with every applicable indicator declared `unaddressed`.
 *
 * This exists because `routes.yaml` is not portable and reads as though it is. It declares
 * twenty-odd indicators `partial` with gaps describing precisely what *this* repository's
 * collectors do and do not establish. Someone who clones the harness for their own boundary
 * and edits the profile inherits every one of those claims — and they are not true of their
 * environment. That is a correctness problem rather than an ergonomic one, because the whole
 * argument for the coverage report is that the declarations behind it are true.
 *
 * So the honest starting point for a new adopter is that nothing has been assessed yet. A
 * generated baseline says exactly that for all forty-six indicators, validates, and produces
 * a coverage report reading `unaddressed 46` on the first run — which is not a failure of the
 * tool but an accurate description of a program on its first day. Every promotion from
 * there is then something a person did deliberately, which is the same discipline the
 * `automated` level already enforces, applied to onboarding.
 *
 * The indicator statement is emitted as a comment above each route so the author can read
 * what they are declaring against without opening the catalog. It is a restatement of the
 * pinned ruleset, which this repository otherwise refuses to do — permissible only because
 * the file is generated and regenerating is the fix. The header records the ruleset version
 * it came from so a stale baseline is visible rather than silently wrong.
 */

/** Wraps text to a width, for emitting readable YAML comments and block scalars. */
function wrap(text, width, indent) {
  const words = String(text).replace(/\s+/g, ' ').trim().split(' ');
  const lines = [];
  let line = '';
  for (const word of words) {
    if (line && line.length + word.length + 1 > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.map((l) => `${indent}${l}`);
}

const REASON =
  'Generated baseline: nobody has assessed this indicator for this environment yet. This is an ' +
  'accurate statement rather than a placeholder, and it should stay until someone decides how the ' +
  'indicator is evidenced here.';

function nextFor(indicator) {
  return (
    `Decide how this is evidenced in this environment. If a check can settle part of it, wire one and ` +
    `move this route to "partial" with the remainder named under "unautomated". If it is a judgment ` +
    `rather than a measurement, move it to "manual" with an owner, an artifact and a reason automation ` +
    `is the wrong tool. Theme ${indicator.theme}: ${indicator.theme_name}.`
  );
}

/**
 * Builds the baseline YAML text for a certification class.
 *
 * Returns a string rather than writing, so the caller decides where it lands and the
 * generator stays testable.
 */
export function buildBaseline({ klass = 'c', now = new Date() } = {}) {
  const { indicators, counts } = catalog({ klass });
  const provenance = rulesProvenance();
  const applicable = indicators.filter((i) => i.applicable);

  const out = [];
  out.push('# Routing baseline — every applicable indicator, unaddressed.');
  out.push('#');
  out.push(...wrap(
    'Generated by `ksi routes baseline`. This is a starting point for a new boundary, not a ' +
      'description of one. Every indicator below says that nobody has assessed it yet, which is ' +
      'true on day one and stops being true the moment someone edits it.',
    96,
    '# '
  ));
  out.push('#');
  out.push(...wrap(
    'Do not copy this repository\'s own routes.yaml instead. That file declares what these ' +
      'collectors establish about the environment they were written for, and inheriting those ' +
      'claims for a different boundary would make the coverage report describe somewhere else.',
    96,
    '# '
  ));
  out.push('#');
  out.push(`# Ruleset:   FedRAMP Consolidated Rules ${provenance.version} (updated ${provenance.last_updated})`);
  out.push(`# Digest:    sha256:${provenance.sha256.slice(0, 32)}`);
  out.push(`# Class:     ${klass.toUpperCase()} — ${applicable.length} applicable of ${counts.total}`);
  out.push(`# Generated: ${now.toISOString().slice(0, 10)}`);
  out.push('#');
  out.push(...wrap(
    `${ALL_CHECKS.length} checks are implemented and none is claimed below. \`ksi routes validate\` will ` +
      'warn about each one — that warning is the backlog, and it goes away as you route them.',
    96,
    '# '
  ));
  out.push('');

  let theme = null;
  for (const indicator of applicable) {
    if (indicator.theme !== theme) {
      theme = indicator.theme;
      out.push(`# ${'─'.repeat(92)}`);
      out.push(`# ${theme} — ${indicator.theme_name}`);
      out.push(`# ${'─'.repeat(92)}`);
      out.push('');
    }

    out.push(`# ${indicator.name}${indicator.optional ? ' (optional at this class)' : ''}`);
    out.push(...wrap(indicator.statement ?? '', 94, '#   '));
    out.push(`#   ${indicator.controls.length} mapped 800-53 control(s)`);
    out.push(`${indicator.id}:`);
    out.push('  coverage: unaddressed');
    out.push('  reason: >');
    out.push(...wrap(REASON, 92, '    '));
    out.push('  next: >');
    out.push(...wrap(nextFor(indicator), 92, '    '));
    out.push('');
  }

  return `${out.join('\n')}\n`;
}
